version: '3.8'

services:
  sophia-chat-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sophia-chat-backend
    restart: "unless-stopped"
    ports:
      - "8080:8080" # Change to "8081:8080" if 8080 is taken
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      # Persistent data for databases
      - ./data:/app/data
      # Config (read-only)
      - ./config:/app/config:ro

# Usage:
# ======
# 1. Create a .env file with your OPENROUTER_API_KEY.
# 2. Run: docker-compose -f docker-compose.mvp.yml up --build
# 3. Open your browser to http://localhost:8080
