"""Enqueue a single explicit file-write test task into the persistent SQLite queue.

This script uses the same SimplePersistentQueue API as the worker.
It creates a simple instruction that asks the planner to return a JSON-only plan
that calls tool_file_system.write_file to create `scripts/tui_by_sophia.py`.
"""
from pathlib import Path
import json
import sys

from core.simple_persistent_queue import SimplePersistentQueue


def main():
    queue = SimplePersistentQueue(db_path=".data/tasks.sqlite")

    # File we want Sophia to create
    target_path = "scripts/tui_by_sophia.py"
    file_content = (
        "# Created by Sophia via planner -> kernel\n"
        "print('Hello from Sophia-created file')\n"
    )

    instruction = (
        "Please return a JSON-only plan (an array) where each item is an object with keys:"
        " 'tool_name' (string), 'method_name' (string), and 'arguments' (object).\n"
        "Create exactly one step that calls tool_file_system.write_file to create the file"
        f" at '{target_path}' with the following content (exactly):\n\n{file_content}\n\n"
        "Output ONLY the JSON array and nothing else. Example output (use exactly this schema):\n"
        "[{\"tool_name\": \"tool_file_system\", \"method_name\": \"write_file\", \"arguments\": {\"path\": \"scripts/x.py\", \"content\": \"print(\\\"hi\\\")\"}}]"
    )

    payload = {
        "instruction": instruction,
        "origin": "user_input",
    }

    tid = queue.enqueue(payload, priority=50)
    print(f"Enqueued explicit file-write task id: {tid}")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"Failed to enqueue: {e}", file=sys.stderr)
        raise
#!/usr/bin/env python3
"""Enqueue a strict file-write test task into the persistent queue.
This script uses core.simple_persistent_queue.SimplePersistentQueue to add a new task.
"""
import json
from core.simple_persistent_queue import SimplePersistentQueue

QUEUE_DB = ".data/tasks.sqlite"

if __name__ == "__main__":
    q = SimplePersistentQueue(db_path=QUEUE_DB)

    # Small sample Python file content that Sophia should write
    file_content = (
        "# Auto-generated by Sophia planner test\n"
        "def hello():\n"
        "    print('Hello from Sophia-generated TUI')\n"
        "\n"
        "if __name__ == '__main__':\n"
        "    hello()\n"
    )

    # Construct a payload that KernelWorker will interpret (user_input)
    user_instruction = (
        "Please produce EXACTLY a JSON array (and nothing else) named 'plan' which is an array of tool calls.\n"
        "The plan must contain one step that uses the plugin 'tool_file_system' and the method 'write_file' to create the file\n"
        "'scripts/tui_by_sophia.py' with the provided content.\n\n"
        "JSON schema example:\n"
        "[{\n"
        "  \"tool_name\": \"tool_file_system\",\n"
        "  \"method_name\": \"write_file\",\n"
        "  \"arguments\": {\n"
        "    \"path\": \"scripts/tui_by_sophia.py\",\n"
        "    \"content\": \"<file content here>\"\n"
        "  }\n"
        "}]\n\n"
        "Replace <file content here> with the exact file content I provided below. DO NOT add any commentary."
    )

    payload = {
        "instruction": user_instruction + "\n\nFILE_CONTENT_START\n" + file_content + "\nFILE_CONTENT_END",
        "origin": "user_input",
        "metadata": {"test": "planner-json-repair"},
    }

    task_id = q.enqueue(payload, priority=10)
    print(f"Enqueued file-write test task id: {task_id}")
