# Gemini Model Configuration
model:
  name: "gemini-1.5-flash-latest"
  temperature: 0.7

# Memory and Prompt Paths
paths:
  jules_md: "memory/JULES.md"
  agents_md: "memory/AGENTS.md"
  system_prompt: "core/system_prompt.py"