name: CI

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv pip install -r requirements.in

      - name: Lint with ruff
        run: ruff check .

      - name: Check formatting with ruff
        run: ruff format --check .

      - name: Run unit tests
        run: PYTHONPATH=. pytest

      - name: Run E2E test
        id: e2e_test
        run: python scripts/run_e2e_test.py
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

      - name: Cleanup Docker environment
        if: always() && steps.e2e_test.conclusion != 'skipped'
        run: docker compose -f docker-compose.yml down --volumes
